import Head from "next/head";
import styled from "@emotion/styled";
import AboutSection from "@/components/AboutSection";
import PartnerSection from "@/components/PertnersSection";
import MeSection from "@/components/MeSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AboutSection />
      <PartnerSection />
      <MeSection />
    </>
  );
}

const StyledHeader = styled.header``;

// width: 100%;
// padding: 0px 24px 0px 2px;
